"""empty message

Revision ID: 7812cbe41b5d
Revises: b8eb0d46f3e3
Create Date: 2018-08-13 09:43:31.279000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7812cbe41b5d'
down_revision = 'b8eb0d46f3e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bookName', sa.String(length=120), nullable=True),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_bookName'), 'book', ['bookName'], unique=True)
    op.create_index(op.f('ix_book_description'), 'book', ['description'], unique=True)
    op.create_index(op.f('ix_book_image'), 'book', ['image'], unique=True)
    op.create_table('genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('genre', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genre_genre'), 'genre', ['genre'], unique=True)
    op.create_index(op.f('ix_genre_type'), 'genre', ['type'], unique=True)
    op.create_table('genres',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'book_id')
    )
    op.create_table('library',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'book_id')
    )
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_table('library')
    op.drop_table('genres')
    op.drop_index(op.f('ix_genre_type'), table_name='genre')
    op.drop_index(op.f('ix_genre_genre'), table_name='genre')
    op.drop_table('genre')
    op.drop_index(op.f('ix_book_image'), table_name='book')
    op.drop_index(op.f('ix_book_description'), table_name='book')
    op.drop_index(op.f('ix_book_bookName'), table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###
