"""users table

Revision ID: b8eb0d46f3e3
Revises: 
Create Date: 2018-08-13 00:29:17.226000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from werkzeug.security import generate_password_hash

revision = 'b8eb0d46f3e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=64), nullable=True),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('password_hash', sa.String(length=128), nullable=True),
                    sa.Column('role', sa.String(length=128), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###

    op.bulk_insert(user_table,
                   [
                       {'username': 'jsmith',
                        'email': 'admin@example.com', 'phone': '09460292951',
                        'password_hash': generate_password_hash('hello'), 'role': 'admin'},
                       {'username': 'hello Smith',
                        'email': 'admin1@example.com', 'phone': '09460292951',
                        'password_hash': generate_password_hash('hello'), 'role': 'user'},
                   ]
                   )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
