"""empty message

Revision ID: e5de96f11294
Revises: 7812cbe41b5d
Create Date: 2018-08-13 09:49:10.648000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5de96f11294'
down_revision = '7812cbe41b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_category',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'book_id')
    )
    op.drop_table('genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('genre_id', sa.INTEGER(), nullable=False),
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], [u'book.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], [u'genre.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'book_id')
    )
    op.drop_table('book_category')
    # ### end Alembic commands ###
